import img1 from '../assets/items/1.jpg';
import img2 from '../assets/items/2.jpg';
import img3 from '../assets/items/3.jpg';
import img4 from '../assets/items/4.jpg';
import img5 from '../assets/items/5.jpg';
import img6 from '../assets/items/6.jpg';
import img7 from '../assets/items/7.jpg';
import img8 from '../assets/items/8.jpg';
import img9 from '../assets/items/9.jpg';
import img10 from '../assets/items/10.jpg';
import img11 from '../assets/items/11.jpg';
import img12 from '../assets/items/12.jpg';
import img13 from '../assets/items/13.jpg';
import img14 from '../assets/items/14.jpg';
import img17 from '../assets/items/17.jpg';
import img21 from '../assets/items/21.jpg';
import img22 from '../assets/items/22.jpg';
import img23 from '../assets/items/23.jpg';
import img25 from '../assets/items/25.jpg';
import img26 from '../assets/items/26.jpg';

const items = [
  {
    id: 1,
    name: 'Curabitur non',
    imageUrl: img1,
    price: 54,
    sofas: true,
    bedroom: true,
    furniture: false,
    coffeeTable: false,
    sale: true,
  },
  {
    id: 2,
    name: 'Donec cursus',
    imageUrl: img2,
    price: 15,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 3,
    name: 'External/Affiliate Product',
    imageUrl: img3,
    price: 8,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: true,
  },
  {
    id: 4,
    name: 'Grouped Product',
    imageUrl: img4,
    price: 12,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 5,
    name: 'Iaculis orci',
    imageUrl: img5,
    price: 35,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 6,
    name: 'Laoreet ultrices',
    imageUrl: img6,
    price: 35,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 7,
    name: 'Maecenas consequat',
    imageUrl: img7,
    price: 35,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 8,
    name: 'Modular Modern',
    imageUrl: img8,
    price: 9,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 9,
    name: 'Modular Modern',
    imageUrl: img9,
    price: 9,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 10,
    name: 'Modular Modern',
    imageUrl: img10,
    price: 9,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 11,
    name: 'Modular Modern',
    imageUrl: img11,
    price: 2,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: true,
  },
  {
    id: 12,
    name: 'Modular Modern',
    imageUrl: img12,
    price: 600,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 13,
    name: 'Nisi vitae',
    imageUrl: img13,
    price: 35,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 14,
    name: 'Patient sofa',
    imageUrl: img14,
    price: 35,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 15,
    name: 'Modular Modern',
    imageUrl: img9,
    price: 9,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: false,
  },
  {
    id: 16,
    name: 'Modular Modern',
    imageUrl: img10,
    price: 14,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: false,
  },
  {
    id: 17,
    name: 'Modular Modern',
    imageUrl: img17,
    price: 13,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: false,
  },
  {
    id: 18,
    name: 'Modular Modern',
    imageUrl: img11,
    price: 2,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: true,
  },
  {
    id: 19,
    name: 'Modular Modern',
    imageUrl: img3,
    price: 10,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: false,
  },
  {
    id: 20,
    name: 'Modular Modern',
    imageUrl: img12,
    price: 7,
    furniture: true,
    coffeeTable: false,
    sofas: false,
    bedroom: false,
    sale: true,
  },
  {
    id: 21,
    name: 'Praesent at',
    imageUrl: img21,
    price: 15,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 22,
    name: 'scelerisque accumsan',
    imageUrl: img22,
    price: 12,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: true,
  },
  {
    id: 23,
    name: 'Urna in eros',
    imageUrl: img23,
    price: 12,
    furniture: true,
    coffeeTable: true,
    sofas: false,
    bedroom: false,
    sale: true,
  },
  {
    id: 24,
    name: 'Variable Product',
    imageUrl: img17,
    price: 8,
    furniture: true,
    coffeeTable: true,
    sofas: true,
    bedroom: true,
    sale: false,
  },
  {
    id: 25,
    name: 'Variable Product – Color',
    imageUrl: img25,
    price: 30,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: true,
  },
  {
    id: 26,
    name: 'Variable Product – Image',
    imageUrl: img26,
    price: 30,
    furniture: false,
    coffeeTable: false,
    sofas: true,
    bedroom: true,
    sale: false,
  },
];

export default items;
